-- NotificationType window updates
DO $$
BEGIN
  BEGIN
    ALTER TYPE "NotificationType" RENAME VALUE 'VISA_EXPIRING_90_DAYS' TO 'VISA_EXPIRING_60_DAYS';
  EXCEPTION WHEN invalid_parameter_value THEN
    -- already renamed or value does not exist
    NULL;
  END;
END $$;

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VISA_EXPIRING_60_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RIGHT_TO_WORK_RECHECK_60_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RIGHT_TO_WORK_RECHECK_30_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RIGHT_TO_WORK_RECHECK_7_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_ENDING_60_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_ENDING_30_DAYS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_ENDING_7_DAYS';

-- Document reminder kinds
ALTER TYPE "DocumentExpiryReminderKind" ADD VALUE IF NOT EXISTS 'BEFORE_60';

-- Metadata-only storage fields
ALTER TABLE "Document"
ADD COLUMN IF NOT EXISTS "mimeType" TEXT,
ADD COLUMN IF NOT EXISTS "sizeBytes" INTEGER,
ADD COLUMN IF NOT EXISTS "fileHash" TEXT;

ALTER TABLE "DocumentVault"
ADD COLUMN IF NOT EXISTS "mimeType" TEXT,
ADD COLUMN IF NOT EXISTS "sizeBytes" INTEGER,
ADD COLUMN IF NOT EXISTS "fileHash" TEXT;

ALTER TABLE "Document" DROP COLUMN IF EXISTS "fileData";
ALTER TABLE "DocumentVault" DROP COLUMN IF EXISTS "fileData";
